#!/bin/bash

cd "$(dirname $0)/litmus/auto"

cross () {
    v=$(for p in $1; do
            for t in $2; do
                echo -n "$p$t,"
            done
        done)
    v=${v%,}
    echo $v
}

# ensure that we don't generate tests mixing atomic and nonatomic ops

pod=$(cross 'PodRR PodRW PodWW PodWR' 'NA AA AN NN')
pos=$(cross 'PosRR PosRW PosWW PosWR' 'AA NN')
po="$pod,$pos"
echo $po
com=$(cross 'Fre Rfe Wse' 'AA NN')

diycross7 -oneloc -bell ../../ocaml.bell $po $com
diycross7 -oneloc -bell ../../ocaml.bell $com $po $com
diycross7 -oneloc -bell ../../ocaml.bell $po $com $po $com
diycross7 -oneloc -bell ../../ocaml.bell $com $po $com $po $com
diycross7 -oneloc -bell ../../ocaml.bell $po $com $po $com $po $com
